name: linux

on:
  push:
    branches: [release]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: test python:${{ matrix.python-version }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: run tests
        run: pdm run test

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"

      - name: deploy sdist
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pdm build --no-wheel
          pdm run deploy_sdist

      - name: build wheel
        uses: RalfG/python-wheels-manylinux-build@v0.5.0
        with:
          python-versions: cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311

      - name: deploy wheels
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m pip install twine
          python3 -m twine upload --skip-existing dist/*-manylinux*.whl
