name: linux

on:
  push:
    branches: [release]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: test python:${{ matrix.python-version }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install deps
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest

      - name: run tests
        run: python3 setup.py test -f tests -a "-q -x"

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install deps
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install twine

      - name: build sdist
        run: |
          python3 setup.py sdist
          mv dist sdist

      - name: build wheel
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
        with:
          python-versions: cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311

      - name: deploy
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m twine upload --skip-existing dist/*-manylinux*.whl
          python3 -m twine upload --skip-existing sdist/*.tar.gz
